### ISSUE TITLE
Installed Fresh Server get this error.

### ISSUE THREAD

**Issue by SolidSnake916** [NyaaCat/RPGitems-reloaded#125]
Upon following the tutorial to create item first command issued gives error, cant continue past that.

issued server command: /rpgitem icecard create
[23:57:28] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[23:57:28] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:57:28] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:57:28] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:57:28] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:57:28] [Server thread/WARN]: 	at think.rpgitems.commands.Commands.exec(Commands.java:186)
[23:57:28] [Server thread/WARN]: 	at think.rpgitems.Plugin.onCommand(Plugin.java:129)
[23:57:28] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[23:57:28] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[23:57:28] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:625)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1297)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1157)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(SourceFile:37)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(SourceFile:9)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[23:57:28] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:57:28] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:683)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:360)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:639)
[23:57:28] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:543)
[23:57:28] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:57:28] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
[23:57:28] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:360)
[23:57:28] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.<init>(RPGItem.java:113)
[23:57:28] [Server thread/WARN]: 	at think.rpgitems.item.ItemManager.newItem(ItemManager.java:186)
[23:57:28] [Server thread/WARN]: 	at think.rpgitems.Handler.createItem(Handler.java:90)
[23:57:28] [Server thread/WARN]: 	... 22 more

**Comment by RecursiveG** [comment]
You have to use spigot server instead of standard craftbukkit server.
