### ISSUE TITLE
WHO CAN HELP ME

### ISSUE THREAD

**Issue by reply7251** [NyaaCat/RPGitems-reloaded#175]
I have a problem.
I can't use the command /rpgitem xxx create.
I never create a rpgitem.
This is my logs:
[06:06:03] [Server thread/INFO]: reply7251 issued server command: /rpgitem 123 create
[06:06:03] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[06:06:03] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:06:03] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[06:06:03] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06:06:03] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[06:06:03] [Server thread/WARN]: 	at think.rpgitems.commands.Commands.exec(Commands.java:186)
[06:06:03] [Server thread/WARN]: 	at think.rpgitems.Plugin.onCommand(Plugin.java:130)
[06:06:03] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[06:06:03] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[06:06:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[06:06:03] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[06:06:03] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:688)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643)
[06:06:03] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547)
[06:06:03] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[06:06:03] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setUnbreakable(Z)V
[06:06:03] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:379)
[06:06:03] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.<init>(RPGItem.java:115)
[06:06:03] [Server thread/WARN]: 	at think.rpgitems.item.ItemManager.newItem(ItemManager.java:189)
[06:06:03] [Server thread/WARN]: 	at think.rpgitems.Handler.createItem(Handler.java:88)
[06:06:03] [Server thread/WARN]: 	... 22 more

And my version is 1.10.2.
I have already download again and again, use another and another RPGitems-reloaded version.
It still like this.
Please help me.

**Comment by cyilin** [comment]
The latest version is for spigot 1.11, please use rpgitem 1.10-v3.5.143 for spigot 1.10.x server
https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.10-v3.5.143
