### ISSUE TITLE
WHO CAN HELP ME(x2)

### ISSUE THREAD

**Issue by reply7251** [NyaaCat/RPGitems-reloaded#176]
Sorry,
I have already changed the RPGitem's version to v3.5.143 (1.10 branch),
but I still can't use the command:
/rpgitem xxxx create

[20:26:55] [Server thread/INFO]: reply7251 issued server command: /rpgitem Test1 create
[20:26:55] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[20:26:55] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:26:55] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:26:55] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:26:55] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[20:26:55] [Server thread/WARN]: 	at think.rpgitems.commands.Commands.exec(Commands.java:186)
[20:26:55] [Server thread/WARN]: 	at think.rpgitems.Plugin.onCommand(Plugin.java:130)
[20:26:55] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[20:26:55] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[20:26:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[20:26:55] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:26:55] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:688)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643)
[20:26:55] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547)
[20:26:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[20:26:55] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
[20:26:55] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:379)
[20:26:55] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.<init>(RPGItem.java:115)
[20:26:55] [Server thread/WARN]: 	at think.rpgitems.item.ItemManager.newItem(ItemManager.java:189)
[20:26:55] [Server thread/WARN]: 	at think.rpgitems.Handler.createItem(Handler.java:88)
[20:26:55] [Server thread/WARN]: 	... 22 more
[20:27:23] [Server thread/INFO]: RPGItem v3.5.143 (1.10 branch)

Copyright ? 2016 NyaaCat Developers
Copyright ? 2013 TheCreeperOfRedstone
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Report Bugs At: https://github.com/NyaaCat/RPGitems-reloaded/issues[m

**Comment by cyilin** [comment]
See #125
