### ISSUE TITLE
1.8.x compatibility check

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#2]
The latest source code v3.5 is compiled against bukkit 1.7.2.

Though @RecursiveG has updated to spigot 1.8.7 but we still need to do some compatibility check to ensure full functionality.

For example, on 1.8 servers the default config missed an entry for `language` and cause the following error.

```
[00:05:15] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to RPG_Items v3.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:296) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:156) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [spigot-1.8.7.jar:git-Spigot-3ccbe77-a6a57a9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.NullPointerException
        at think.rpgitems.data.Locale.getPlayerLocale(Locale.java:158) ~[?:?]
```

Looks it tends to get player locale but the method changed. set `language` in `config.yml` shall avoid this message. There may be more issues like this.

**Comment by Taiterio** [comment]
Fixed the error that occurred in commit 09d02f142598560e7daec84b96afb29929e51f44. The problem was that the plugin tried to check for the "language" value in the config, which was not set. I now standardize the language to en_GB.

Will do some more extensive testing to see if any parts of the plugin could cause problems with the update to 1.8
