### ISSUE TITLE
如何将rpg物品保存为无法破坏且破损值固定

### ISSUE THREAD

**Issue by imjtq** [NyaaCat/RPGitems-reloaded#212]
如题，我想利用破损材质改变rpg的外观，但是设定了耐久值的rpg不仅lore的条会变，物品本身的damage也会改变，这样材质就会变了，如何锁定物品本身的damage同时具有耐久功能，而且带有nbt标签unbreakable：1

**Comment by RecursiveG** [comment]
该功能尚未实现
#113

**Comment by imjtq** [comment]
那预计何时能实现，如果近期的话我就等等再做rpg

**Comment by Librazy** [comment]
您的服务器什么版本的？
具体的需求是什么？

**Comment by cyilin** [comment]
在这里 https://github.com/NyaaCat/RPGitems-reloaded/issues/197

**Comment by imjtq** [comment]
不好意思没看见之前那个，谢了

**Comment by imjtq** [comment]
等等。。。为什么我1.10spigot用1.11的版本create的时候没反应，后台提示这个
[13:22:55 WARN]: java.lang.reflect.InvocationTargetException
[13:22:55 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[13:22:55 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[13:22:55 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[13:22:55 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:22:55 WARN]:        at think.rpgitems.commands.Commands.exec(Commands.java:1
86)
[13:22:55 WARN]:        at think.rpgitems.Plugin.onCommand(Plugin.java:133)
[13:22:55 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[13:22:55 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[13:22:55 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchC
ommand(CraftServer.java:646)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handle
Command(PlayerConnection.java:1348)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(Play
erConnection.java:1183)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:45)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(Pack
etPlayInChat.java:1)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1
.run(SourceFile:13)
[13:22:55 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[13:22:55 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFil
e:45)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(Minec
raftServer.java:733)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(Dedic
atedServer.java:399)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(Minec
raftServer.java:672)
[13:22:55 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(Min
ecraftServer.java:571)
[13:22:55 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:22:55 WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.me
ta.ItemMeta.setUnbreakable(Z)V
[13:22:55 WARN]:        at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:447)

[13:22:55 WARN]:        at think.rpgitems.item.RPGItem.<init>(RPGItem.java:128)
[13:22:55 WARN]:        at think.rpgitems.item.ItemManager.newItem(ItemManager.j
ava:189)
[13:22:55 WARN]:        at think.rpgitems.Handler.createItem(Handler.java:125)
[13:22:55 WARN]:        ... 22 more
>

**Comment by Librazy** [comment]
旧版服务器是不能用新版的插件的。1.10已经转入后期维护了，暂时还没有将功能backport到1.10的准备。

**Comment by imjtq** [comment]
那么也就是说那个添加材质和nbttag的功能不准备添加到1.10喽
