### ISSUE TITLE
Issue enabling up on the server

### ISSUE THREAD

**Issue by Demonkid1112** [NyaaCat/RPGitems-reloaded#213]
I am trying to load it up on version 1.11.2, I'm not sure if thats the issue right there however this is the error I am currently getting this as the loading up error

`[15:26:37] [Server thread/INFO]: [RPGItems] Enabling RPGItems v3.5.203
[15:26:37] [Server thread/INFO]: [RPGItems] The updater is currently under maintenance,
[15:26:37] [Server thread/INFO]: [RPGItems] Please check www.github.com/NyaaCat/RPGitems-reloaded for updates.
[15:26:37] [Server thread/ERROR]: Error occurred while enabling RPGItems v3.5.203 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
	at think.rpgitems.Plugin.onEnable(Plugin.java:103) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:729) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.Bukkit.reload(Bukkit.java:549) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:629) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1286) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1146) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_112]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit-1.11.2.jar:git-Bukkit-257d6cd]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
	... 24 more`

Again not fully sure if there is an issue with the server version or I may be missing some plugin but I would love to have this on a server I am currently working on!

**Comment by cyilin** [comment]
RPGItems is not compatible with craftbukkit, please use spigot.
