### ISSUE TITLE
1.7.x servers

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#22]
Is there any necessity to build and test against bukkit & spigot 1.7.2 servers? There are still a LOT of 1.7.2 servers running in offline mode.

Though this plugin can be run on 1.7.2 in v3.5 but since we have added some new things, not sure it's still 1.7.2 compatible.

**Comment by Taiterio** [comment]
So far none of the changes made since 3.5 should have made it incompatible with 1.7, I'll do some more extensive testing on parts that may have problems though.

**Comment by phoenixlzx** [comment]
Set up v3.5.51 on cb 1.7.2 and get the following error:
```
[23:30:38 WARN]: [RPGItems] Task #27 for RPGItems v3.5.51 generated an exception
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()Ljava/util/Collection;
        at think.rpgitems.power.PowerTicker.run(PowerTicker.java:14) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:587) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
```
