### ISSUE TITLE
求助各位dalao

### ISSUE THREAD

**Issue by ExcitedFrog1s** [NyaaCat/RPGitems-reloaded#224]
是这样的
我写了一个小插件
里面有这么一段代码
`            //点券包（小）
            RPGItem item09=new RPGItem("LotteryItem09",1009);
            item09.setQuality(Quality.UNCOMMON,true);
            item09.addDescription("一个小小的点券包。");
            PowerCommand tokenPowerA = new PowerCommand();  //点券效果1
            tokenPowerA.command="/money give " + player.getName() + "88";
            tokenPowerA.permission="iConomy.accounts.give";
            tokenPowerA.display="§b右键使用获得88点券。";
            PowerConsume consume=new PowerConsume();    //使用完物品后物品自动消失
            item09.addPower(tokenPowerA,true);
            item09.addPower(consume);
            inventory.setItem(9,item09.toItemStack());//塞进9号格子`
然后在运行时
[10:59:54 ERROR]: Could not load 'plugins\PlayerWatcher.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: think/rpgitems/power/Power
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoClassDefFoundError: think/rpgitems/power/Power
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: think.rpgitems.power.Power
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.11.jar:git-Spigot-f950f8e-0a81101]
        ... 6 more
我使用的插件版本是1.11-v.223
spigot服务端为1.11
请问这样的问题如何解决？

附：在代码中引入了：
       import think.rpgitems.item.Quality;
       import think.rpgitems.item.RPGItem;
       import think.rpgitems.power.PowerCommand;
       import think.rpgitems.power.PowerConsume;

**Comment by Librazy** [comment]
看起来你的插件在RPGItem之前载入了，没有读到RPGItem的类定义。在Plugin.yml里设置一下插件的依赖

**Comment by ExcitedFrog1s** [comment]
成功了！谢谢！
