### ISSUE TITLE
創造物品時沒有反應 #3

### ISSUE THREAD

**Issue by NightLame** [NyaaCat/RPGitems-reloaded#241]
已更改成 spitgot1.11 插件版本rpgitem-reloaded-1.11-v.231 但還是無法使用 /rpgitem op1 create ....

**Comment by cyilin** [comment]
请提供spigot的log（logs/latest.log）

**Comment by NightLame** [comment]
[21:27:42] [Server thread/INFO]: Starting minecraft server version 1.11
[21:27:42] [Server thread/INFO]: Loading properties
[21:27:42] [Server thread/INFO]: Default game type: SURVIVAL
[21:27:42] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-16c940b-221508d (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
[21:27:42] [Server thread/INFO]: Debug logging is disabled
[21:27:42] [Server thread/INFO]: Server Ping Player Sample Count: 12
[21:27:42] [Server thread/INFO]: Using 4 threads for Netty based IO
[21:27:42] [Server thread/INFO]: Generating keypair
[21:27:43] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:27:43] [Server thread/INFO]: Using default channel type
[21:27:43] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[21:27:43] [Server thread/INFO]: [CustomShield] Loading CustomShield v1.1
[21:27:43] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[21:27:43] [Server thread/WARN]: [PermissionsEx] This server is in offline mode. Unless this server is configured to integrate with a supported proxy (see http://dft.ba/-8ous), UUIDs *may not be stable*!
[21:27:43] [Server thread/INFO]: [AdvancedLogger] Loading AdvancedLogger v1.7
[21:27:43] [Server thread/INFO]: [RPGItems] Loading RPGItems v3.5.231
[21:27:43] [Server thread/INFO]: [Kycraft] Loading Kycraft v1.0.32
[21:27:43] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.5;4651611
[21:27:43] [Server thread/INFO]: [SuperVanish] Loading SuperVanish v5.9.2
[21:27:43] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5.0-b727
[21:27:44] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:27:44] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:27:44] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[21:27:44] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:27:44] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[21:27:44] [Server thread/INFO]: Preparing level "world"
[21:27:44] [Server thread/INFO]: -------- World Settings For [world] --------
[21:27:44] [Server thread/INFO]: Item Despawn Rate: 6000
[21:27:44] [Server thread/INFO]: Item Merge Radius: 2.5
[21:27:44] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:27:44] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:27:44] [Server thread/INFO]: View Distance: 10
[21:27:44] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:27:44] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:27:44] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:27:44] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:27:44] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:27:44] [Server thread/INFO]: Mob Spawn Range: 4
[21:27:44] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:27:44] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:27:44] [Server thread/INFO]: Random Lighting Updates: false
[21:27:44] [Server thread/INFO]: Structure Info Saving: true
[21:27:44] [Server thread/INFO]: Max TNT Explosions: 100
[21:27:44] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:27:44] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[21:27:44] [Server thread/INFO]: Item Despawn Rate: 6000
[21:27:44] [Server thread/INFO]: Item Merge Radius: 2.5
[21:27:44] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:27:44] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:27:44] [Server thread/INFO]: View Distance: 10
[21:27:44] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:27:44] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:27:44] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:27:44] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:27:44] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:27:44] [Server thread/INFO]: Mob Spawn Range: 4
[21:27:44] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:27:44] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:27:44] [Server thread/INFO]: Random Lighting Updates: false
[21:27:44] [Server thread/INFO]: Structure Info Saving: true
[21:27:44] [Server thread/INFO]: Max TNT Explosions: 100
[21:27:44] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:27:44] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[21:27:44] [Server thread/INFO]: Item Despawn Rate: 6000
[21:27:44] [Server thread/INFO]: Item Merge Radius: 2.5
[21:27:44] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:27:44] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:27:44] [Server thread/INFO]: View Distance: 10
[21:27:44] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:27:44] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:27:44] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:27:44] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:27:44] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:27:44] [Server thread/INFO]: Mob Spawn Range: 4
[21:27:44] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:27:44] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:27:44] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:27:44] [Server thread/INFO]: Random Lighting Updates: false
[21:27:44] [Server thread/INFO]: Structure Info Saving: true
[21:27:44] [Server thread/INFO]: Max TNT Explosions: 100
[21:27:44] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:27:44] [Server thread/INFO]: Preparing start region for level 0 (Seed: -7143994253002048191)
[21:27:45] [Server thread/INFO]: Preparing spawn area: 1%
[21:27:46] [Server thread/INFO]: Preparing spawn area: 21%
[21:27:47] [Server thread/INFO]: Preparing spawn area: 40%
[21:27:48] [Server thread/INFO]: Preparing spawn area: 54%
[21:27:49] [Server thread/INFO]: Preparing spawn area: 69%
[21:27:50] [Server thread/INFO]: Preparing spawn area: 84%
[21:27:51] [Server thread/INFO]: Preparing start region for level 1 (Seed: -7143994253002048191)
[21:27:52] [Server thread/INFO]: Preparing spawn area: 23%
[21:27:53] [Server thread/INFO]: Preparing spawn area: 50%
[21:27:54] [Server thread/INFO]: Preparing spawn area: 80%
[21:27:55] [Server thread/INFO]: Preparing start region for level 2 (Seed: -7143994253002048191)
[21:27:56] [Server thread/INFO]: [CustomShield] Enabling CustomShield v1.1
[21:27:56] [Server thread/INFO]: [CustomShield] Opening Custom Shield...
[21:27:56] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[21:27:56] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[21:27:56] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[21:27:56] [Server thread/INFO]: [AdvancedLogger] Enabling AdvancedLogger v1.7
[21:27:57] [Server thread/INFO]: [m
[21:27:57] [Server thread/INFO]: [0;33;22m==========>[[0;31;1mAVL Terms[0;33;22m]<==========[m
[21:27:57] [Server thread/INFO]: [0;33;22m-> You are not permitted to claim this plugin as your own![m
[21:27:57] [Server thread/INFO]: [0;33;22m-> You are not permitted to decompiling the plugin's sourcecode![m
[21:27:57] [Server thread/INFO]: [0;33;22m-> You are not permitted to modify the code or the plugin and call it your own![m
[21:27:57] [Server thread/INFO]: [0;33;22m-> You are not permitted to redistributing this plugin as your own![m
[21:27:57] [Server thread/INFO]: [0;33;22m=======>[[0;32;1mTerms Accepted![0;33;22m]<=======[m
[21:27:57] [Server thread/INFO]: [m
[21:27:57] [Server thread/INFO]: [0;33;22m[[0;31;1mAdvancedLogger[0;33;22m] [0;32;1mStarted [0;33;1mMetrics [0;32;1msuccessful![m
[21:27:57] [Server thread/INFO]: [0;33;22m[[0;31;1mAdvancedLogger[0;33;22m] [0;33;1mMySQL-Service [0;31;1mdisabled![m
[21:27:57] [Server thread/INFO]: [0;33;22m[[0;31;1mAdvancedLogger[0;33;22m] [0;36;1mVersion: 1.7 [0;32;1mby [0;31;1m[Herbystar][0;32;1m enabled![m
[21:27:57] [Server thread/INFO]: [RPGItems] Enabling RPGItems v3.5.231
[21:27:57] [Server thread/WARN]: [RPGItems] Could not save en_GB.lang to plugins\RPGItems\locale\en_GB.lang because en_GB.lang already exists.
[21:27:57] [Server thread/INFO]: [RPGItems] The updater is currently under maintenance,
[21:27:57] [Server thread/INFO]: [RPGItems] Please check [0;30;1m[3m[21mwww.github.com/NyaaCat/RPGitems-reloaded[m for updates.[m
[21:27:57] [Server thread/INFO]: [Kycraft] Enabling Kycraft v1.0.32
[21:27:57] [Server thread/ERROR]: Error occurred while enabling Kycraft v1.0.32 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
	at com.kunyihua.crafte.Main.SetupVaultEconomy(Main.java:100) ~[?:?]
	at com.kunyihua.crafte.Main.onEnable(Main.java:42) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:373) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_131]
	... 13 more
[21:27:57] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.5;4651611
[21:27:57] [Server thread/INFO]: WEPIF: Updated config file
[21:27:57] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[21:27:57] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_11_R1 as the Bukkit adapter
[21:27:57] [Server thread/INFO]: [SuperVanish] Enabling SuperVanish v5.9.2
[21:27:57] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5.0-b727
[21:27:58] [Server thread/INFO]: -------- World Settings For [spawn] --------
[21:27:58] [Server thread/INFO]: Item Despawn Rate: 6000
[21:27:58] [Server thread/INFO]: Item Merge Radius: 2.5
[21:27:58] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:27:58] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:27:58] [Server thread/INFO]: View Distance: 10
[21:27:58] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:27:58] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:27:58] [Server thread/INFO]: Experience Merge Radius: 3.0
[21:27:58] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[21:27:58] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[21:27:58] [Server thread/INFO]: Mob Spawn Range: 4
[21:27:58] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:27:58] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[21:27:58] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:27:58] [Server thread/INFO]: Random Lighting Updates: false
[21:27:58] [Server thread/INFO]: Structure Info Saving: true
[21:27:58] [Server thread/INFO]: Max TNT Explosions: 100
[21:27:58] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:27:58] [Server thread/INFO]: Preparing start region for level 3 (Seed: 7485076411096877744)
[21:27:58] [Server thread/INFO]: [Multiverse-Core] 4 - World(s) loaded.
[21:27:58] [Server thread/INFO]: [Multiverse-Core] Version 2.5.0-b727 (API v20) Enabled - By Rigby, fernferret, lithium3141, main-- and dumptruckman
[21:27:58] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:27:59] [Server thread/INFO]: Done (15.019s)! For help, type "help" or "?"
[21:30:38] [User Authenticator #1/INFO]: UUID of player qazxc_110116 is 7773720c-41e6-3918-a67e-debdb52d19b4
[21:30:38] [Server thread/INFO]: qazxc_110116[/125.231.164.101:50575] logged in with entity id 377 at ([world]203.5, 69.0, 243.5)
[21:30:46] [Server thread/INFO]: qazxc_110116 issued server command: /gamemode 1
[21:30:47] [Server thread/INFO]: qazxc_110116 has just earned the achievement [Taking Inventory]
[21:30:48] [Server thread/INFO]: Opped qazxc_110116
[21:30:50] [Server thread/INFO]: qazxc_110116 issued server command: /gamemode 1
[21:30:50] [Server thread/INFO]: [qazxc_110116: Set own game mode to Creative Mode]
[21:31:05] [Server thread/INFO]: qazxc_110116 issued server command: /mv
[21:31:09] [Server thread/INFO]: qazxc_110116 issued server command: /mv tp spawn
[21:31:15] [Server thread/INFO]: qazxc_110116 issued server command: /gamemode 1
[21:31:15] [Server thread/INFO]: [qazxc_110116: Set own game mode to Creative Mode]
[21:31:21] [Server thread/INFO]: qazxc_110116 issued server command: /rpgitem
[21:31:25] [Server thread/INFO]: qazxc_110116 issued server command: /rpgitem op1 create
[21:31:25] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[21:31:25] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:31:25] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:31:25] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:31:25] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:31:25] [Server thread/WARN]: 	at think.rpgitems.commands.Commands.exec(Commands.java:198)
[21:31:25] [Server thread/WARN]: 	at think.rpgitems.Plugin.onCommand(Plugin.java:96)
[21:31:25] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:31:25] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:31:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:31:25] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:31:25] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
[21:31:25] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
[21:31:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:31:25] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setUnbreakable(Z)V
[21:31:25] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:559)
[21:31:25] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.<init>(RPGItem.java:131)
[21:31:25] [Server thread/WARN]: 	at think.rpgitems.item.ItemManager.newItem(ItemManager.java:188)
[21:31:25] [Server thread/WARN]: 	at think.rpgitems.Handler.createItem(Handler.java:161)
[21:31:25] [Server thread/WARN]: 	... 22 more
[21:34:19] [Server thread/INFO]: qazxc_110116 issued server command: /ip
[21:36:42] [Server thread/INFO]: Stopping the server
[21:36:42] [Server thread/INFO]: Stopping server
[21:36:42] [Server thread/INFO]: [Multiverse-Core] Disabling Multiverse-Core v2.5.0-b727
[21:36:42] [Server thread/INFO]: [SuperVanish] Disabling SuperVanish v5.9.2
[21:36:42] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v6.1.5;4651611
[21:36:42] [Server thread/INFO]: [Kycraft] Disabling Kycraft v1.0.32
[21:36:42] [Server thread/ERROR]: Error occurred while disabling Kycraft v1.0.32 (Is it up to date?)
java.lang.NullPointerException
	at com.kunyihua.crafte.Main.onDisable(Main.java:79) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:273) ~[spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.disablePlugins(CraftServer.java:342) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.stop(MinecraftServer.java:462) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:610) [spigot-1.11.jar:git-Spigot-16c940b-221508d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[21:36:42] [Server thread/INFO]: [RPGItems] Disabling RPGItems v3.5.231
[21:36:43] [Server thread/INFO]: [AdvancedLogger] Disabling AdvancedLogger v1.7
[21:36:43] [Server thread/INFO]: [0;33;22m[[0;31;1mAdvancedLogger[0;33;22m] [0;36;1mVersion: 1.7 [0;32;1mby [0;31;1m[Herbystar][0;31;1m disabled![m
[21:36:43] [Server thread/INFO]: [PermissionsEx] Disabling PermissionsEx v1.23.4
[21:36:43] [Server thread/INFO]: [CustomShield] Disabling CustomShield v1.1
[21:36:43] [Server thread/INFO]: [CustomShield] closeing Custom Shield...
[21:36:43] [Server thread/INFO]: Saving players
[21:36:43] [Server thread/INFO]: qazxc_110116 lost connection: Server closed
[21:36:43] [Server thread/INFO]: qazxc_110116 left the game
[21:36:43] [Server thread/INFO]: Saving worlds
[21:36:43] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[21:36:43] [Server thread/INFO]: Saving chunks for level 'world_nether'/Nether
[21:36:43] [Server thread/INFO]: Saving chunks for level 'world_the_end'/The End
[21:36:43] [Server thread/INFO]: Saving chunks for level 'spawn'/Overworld

**Comment by cyilin** [comment]
请使用最新版的spigot 1.11或spigot 1.11.2，您使用的是spigot 1.11最初发布的版本，spigot在更新1.11后又更改过API。
