### ISSUE TITLE
Error from 1.12-v3.6.268 i downloaded in release page

### ISSUE THREAD

**Issue by juliu123** [NyaaCat/RPGitems-reloaded#260]
[17:54:15] [Server thread/ERROR]: Could not load 'plugins\rpgitem-reloaded-1.12-v.268.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: NyaaCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
[17:54:15] [Server thread/INFO]: Set PluginClassLoader as parallel capable

**Comment by cyilin** [comment]
you need to install NyaaCore and LangUtils 
https://github.com/NyaaCat/NyaaCore/releases
https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/

**Comment by Librazy** [comment]
And sorry for this version to be shown in releases page. Version 3.6 is under development and should work but may contain some bug. Please use version 3.5 for now.
