### ISSUE TITLE
Bug with recipes  with 1.12.2  

### ISSUE THREAD

**Issue by MyCraftServer** [NyaaCat/RPGitems-reloaded#263]
Hi, when i create a recipe for an item i get this error when i do /rpgitem reload, i use 1.12.2 and rpgitem-reloaded-1.12-v.268

I have testes and this happens with all the recipes

`RPGItems (3.6.268) ItemManager.load
java.lang.IllegalStateException: Duplicate recipe ignored with ID rpgitems:v2craft1_1510830080256
	at net.minecraft.server.v1_12_R1.CraftingManager.a(CraftingManager.java:149)
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:58)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.addRecipe(CraftServer.java:1099)
	at org.bukkit.Bukkit.addRecipe(Bukkit.java:585)
	at think.rpgitems.item.RPGItem.resetRecipe(RPGItem.java:467)
	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:598)
	at think.rpgitems.item.RPGItem.<init>(RPGItem.java:259)
	at think.rpgitems.item.ItemManager.load(ItemManager.java:89)
	at think.rpgitems.item.ItemManager.reload(ItemManager.java:46)
	at think.rpgitems.Handler.reload(Handler.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:202)
	at think.rpgitems.commands.RPGCommandReceiver.onCommand(RPGCommandReceiver.java:177)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:651)
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1392)
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1227)
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Librazy** [comment]
Custom recipe by plugin in 1.12/1.13+ is not recommend. Recipe support in RPGItems main plugin may be removed in future.
