### ISSUE TITLE
spigot 1.12.2服务端无法加载插件，望解决！

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [NyaaCat/RPGitems-reloaded#272]
```
[10:55:35] [Server thread/ERROR]: Could not load 'plugins\NyaaCore-v4.1.62-mc1.12.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: LangUtils
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[10:55:35] [Server thread/ERROR]: Could not load 'plugins\rpgitem-reloaded-1.12-v.276.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: NyaaCore
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-3d850ec-dccd276]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
```

**Comment by cyilin** [comment]
see https://github.com/NyaaCat/RPGitems-reloaded/issues/260
