### ISSUE TITLE
Crash at 1.7.2 MCPC+ MinecraftForge v10.12.2.1147

### ISSUE THREAD

**Issue by MlgmXyysd** [NyaaCat/RPGitems-reloaded#279]
[16:03:01] [Server thread/INFO]: mlgmxyysd issued server command: /rpgitem dexpcard2h create
[16:03:01] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[16:03:01] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:03:01] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:03:01] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:03:01] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:03:01] [Server thread/WARN]: 	at think.rpgitems.commands.Commands.exec(Commands.java:186)
[16:03:01] [Server thread/WARN]: 	at think.rpgitems.Plugin.onCommand(Plugin.java:130)
[16:03:01] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:03:01] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175)
[16:03:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1360)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1127)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:206)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:953)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:646)
[16:03:01] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[16:03:01] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[16:03:01] [Server thread/WARN]: 	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:339)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:38)
[16:03:01] [Server thread/WARN]: 	at net.minecraft.item.crafting.ShapelessRecipes.toBukkitRecipe(ShapelessRecipes.java:15)
[16:03:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R1.inventory.RecipeIterator.next(RecipeIterator.java:32)
[16:03:01] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R1.inventory.RecipeIterator.next(RecipeIterator.java:10)
[16:03:01] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.resetRecipe(RPGItem.java:272)
[16:03:01] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:374)
[16:03:01] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.<init>(RPGItem.java:115)
[16:03:01] [Server thread/WARN]: 	at think.rpgitems.item.ItemManager.newItem(ItemManager.java:186)
[16:03:01] [Server thread/WARN]: 	at think.rpgitems.Handler.createItem(Handler.java:91)
[16:03:01] [Server thread/WARN]: 	... 20 more
RPGitems v3.5.265版本

**Comment by cyilin** [comment]
看出错位置应该是服务器端的问题，或者和mod有关。
使用git-Cauldron-MCPC-Plus-1.7.2-1.1147.04.90测试没有问题。
