### ISSUE TITLE
Power Shulkerbullet not working

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGitems-reloaded#300]
When using an item with the power shulkerbullet nothing happens. The cooldown still works normally though. When using an item with that power an error appears in the console.

[13:32:02] [Server thread/INFO]: Severdez issued server command: /rpgitem test3 power shulkerbullet 20 20
[13:32:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.5.308
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:942) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Projectile not supported
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.launchProjectile(CraftLivingEntity.java:392) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.launchProjectile(CraftLivingEntity.java:335) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at think.rpgitems.power.PowerShulkerBullet.rightClick(PowerShulkerBullet.java:73) ~[?:?]
	at think.rpgitems.item.RPGItem.rightClick(RPGItem.java:484) ~[?:?]
	at think.rpgitems.Events.onPlayerAction(Events.java:308) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	... 18 more

Same thing with the projectile llamaspit and shulkerbullet. Will post other issues for these powers though.

EDIT: Power Stuck is working. It's just the description is incorrect. I don't know if you didn't inclue a integer for the CHANCE in the '/rpgitem power stuck' command or if you forgot to add it. But after setting the chance to 100% with the set command i realised it works perfectly fine.

**Comment by cyilin** [comment]
fixed in v3.5.310

**Comment by Severdez** [comment]
Yes everything it's working now! Thank you very much!
