### ISSUE TITLE
Projectiles llamaspit and shulkerbullet not working

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGitems-reloaded#301]
When using an item that shoots llamaspit or shulkerbullet with the power projectile, nothing happens and an error appears in the console.

LLAMASPIT:

[13:44:42] [Server thread/INFO]: Severdez issued server command: /rpgitem test3 power projectile llamaspit 20 5 1
[13:44:47] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.5.308
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:942) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Projectile not supported
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.launchProjectile(CraftLivingEntity.java:392) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at think.rpgitems.power.PowerProjectile.fire(PowerProjectile.java:248) ~[?:?]
	at think.rpgitems.power.PowerProjectile.rightClick(PowerProjectile.java:194) ~[?:?]
	at think.rpgitems.item.RPGItem.rightClick(RPGItem.java:484) ~[?:?]
	at think.rpgitems.Events.onPlayerAction(Events.java:308) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	... 18 more

SHULKERBULLET:

[13:45:19] [Server thread/INFO]: Severdez issued server command: /rpgitem test3 power projectile shulkerbullet 20 5 1
[13:45:20] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.5.308
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:942) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Projectile not supported
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.launchProjectile(CraftLivingEntity.java:392) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	at think.rpgitems.power.PowerProjectile.fire(PowerProjectile.java:248) ~[?:?]
	at think.rpgitems.power.PowerProjectile.rightClick(PowerProjectile.java:194) ~[?:?]
	at think.rpgitems.item.RPGItem.rightClick(RPGItem.java:484) ~[?:?]
	at think.rpgitems.Events.onPlayerAction(Events.java:308) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-b32c8f8-4d3bf20]
	... 18 more

**Comment by cyilin** [comment]
please use latest version of spigot 1.11.2

**Comment by Severdez** [comment]
Yeah i realised myself that i used the older Version and updated. It still had the same outcome. Also with the other tickets i opened

**Comment by Severdez** [comment]
Nope I tried updating Spigot via BuildTools and the download on the main site and it still gives me the same error.

**Comment by cyilin** [comment]
@Severdez try rpgitem v3.5.309 https://github.com/NyaaCat/RPGitems-reloaded/releases

**Comment by Severdez** [comment]
The **PROJECTILE** shulkerbullet works perfectly fine now. 

The **POWER** shulkerbullet still gives me an error though:

[14:23:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.5.309
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Projectile not supported
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.launchProjectile(CraftLivingEntity.java:405) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.entity.CraftLivingEntity.launchProjectile(CraftLivingEntity.java:339) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at think.rpgitems.power.PowerShulkerBullet.rightClick(PowerShulkerBullet.java:73) ~[?:?]
	at think.rpgitems.item.RPGItem.rightClick(RPGItem.java:484) ~[?:?]
	at think.rpgitems.Events.onPlayerAction(Events.java:308) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	... 18 more

**Comment by Severdez** [comment]
It's working now thanks!
