### ISSUE TITLE
java.lang.NoClassDefFoundError: javafx/util/Pair

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/RPGitems-reloaded#317]
加载RPGItem时报错
```Java
[20:13:31] [Server thread/INFO]: [RPGItems] Enabling RPGItems v3.6.285
[20:13:31] [Server thread/INFO]: [RPGItems] [RPGItems] WorldGuard version 6.2.1 : 6.2.1;84bc322 found
[20:13:31] [Server thread/INFO]: [WorldGuard] Registering session handler think.rpgitems.support.WGHandler
[20:13:31] [Server thread/INFO]: [RPGItems] Now using language: en_US
[20:13:31] [Server thread/ERROR]: Error occurred while enabling RPGItems v3.6.285 (Is it up to date?)
java.lang.NoClassDefFoundError: javafx/util/Pair
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_162]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_162]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_162]
	at cat.nyaa.nyaacore.CommandReceiver.getAllMethods(CommandReceiver.java:88) ~[?:?]
	at cat.nyaa.nyaacore.CommandReceiver.<init>(CommandReceiver.java:110) ~[?:?]
	at think.rpgitems.commands.RPGCommandReceiver.<init>(RPGCommandReceiver.java:23) ~[?:?]
	at think.rpgitems.Handler.<init>(Handler.java:38) ~[?:?]
	at think.rpgitems.RPGItems.onEnable(RPGItems.java:52) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_162]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PaperSpigot-1.12.2-R0.1.jar:git-Paper-1472]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
	... 19 more
[20:13:31] [Server thread/INFO]: [RPGItems] Disabling RPGItems v3.6.285
```

**Comment by Ghost-chu** [comment]
RPGItem 1.12 lastet build

**Comment by Librazy** [comment]
As a workaround, please use oracle jdk instead of openjdk.

**Comment by ReinWD** [comment]
你的JRE中没有javafx.util.Pair这个类
应该是整个javafx包都没有

jre1.8.0_144中包含有这个类，请检查使用含有javafx包的JDK/JRE
