### ISSUE TITLE
Error when using enderchest command

### ISSUE THREAD

**Issue by mckite** [NyaaCat/RPGitems-reloaded#320]
[01:00:21 INFO]: KitePro issued server command: /enderchest
[01:00:21 ERROR]: Could not pass event InventoryOpenEvent to RPGItems v3.5.319
org.bukkit.event.EventException: null
        at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:79) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-642f6
d2-6103339]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [craftbukkit.jar:git-Spigot-642
f6d2-6103339]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [craftbukkit.jar:git-Spigot-642
f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:766) [c
raftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.EntityPlayer.openContainer(EntityPlayer.java:795) [craftbukkit.jar:git-Spigot-6
42f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:195) [craftbukkit
.jar:git-Spigot-642f6d2-6103339]
        at com.earth2me.essentials.commands.Commandenderchest.run(Commandenderchest.java:23) [EssentialsX-2.15.0.1.jar:?
]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX-2.15.0.1.jar:
?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517) [EssentialsX-2.15.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:430) [EssentialsX-2.15.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at com.massivecraft.massivelag.inject.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:98) [MassiveLag.ja
r:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [craftbukkit.jar:git-Spigot
-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [craftbukkit.jar:git
-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [craftbukkit.jar:git-Spigot-642f
6d2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-642f6d
2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-642f6d2-
6103339]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-642f6
d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_12_R1.InventoryEnderChest.getLocation(InventoryEnderChest.java:18) ~[craftbukkit.jar:
git-Spigot-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.getLocation(CraftInventory.java:504) ~[craftbukkit.j
ar:git-Spigot-642f6d2-6103339]
        at think.rpgitems.Events.onInventoryOpen(Events.java:444) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
        at com.massivecraft.massivelag.inject.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:69) ~[?:?]
        ... 26 more

**Comment by cyilin** [comment]
fixed in 3.5.329
