### ISSUE TITLE
1.13run error?

### ISSUE THREAD

**Issue by engineer1109** [NyaaCat/RPGitems-reloaded#327]
RPGItems (3.6.333) ItemManager.load
java.lang.NullPointerException
	at think.rpgitems.item.ItemManager.load(ItemManager.java:79)
	at think.rpgitems.RPGItems.onEnable(RPGItems.java:75)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:425)
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:339)
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562)
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524)
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423)
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
	at java.lang.Thread.run(Unknown Source)
Enable Failure
Is it incomplete?

**Comment by Librazy** [comment]
As the items/materials changes a lot in 1.13, there may be some problem reading old item config. I'll take care of old item convention once the plugin is stable enough in 1.13 fresh install.
