### ISSUE TITLE
1.13 Error Use Item

### ISSUE THREAD

**Issue by gavemalay233** [NyaaCat/RPGitems-reloaded#334]
When holding RPGitem, right click on the error.
![image](https://user-images.githubusercontent.com/16867767/45089467-79866000-b136-11e8-8edc-5de45df6606e.png)

**System information**
OS: Win7 64Bit
Minecraft Version: 1.13
Java Version: jre1.8.0_181
Plugins Version:
- Essentials-2.x-SNAPSHOT
- ProtocolLib-4.4.0-SNAPSHOT-b414
- Vault-1.6.7
- LangUtils-1.9
- NyaaCore-v6.2.226-mc1.13.1
- rpgitem-reloaded-3.6.415-mc1.13.1
- worldedit-bukkit-7.0.0-SNAPSHOT-dist
- worldguard-legacy-7.0.0-SNAPSHOT-dist

**Error Code**
[17:58:36 ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.6.415-
mc1.13.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:308) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callPlayerInt
eractEvent(CraftEventFactory.java:238) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7a
df7]
        at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractM
anager.java:451) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.jav
a:1227) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:37) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseIt
em.java:1) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10)
~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1
.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:
884) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:
411) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:
819) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.jav
a:717) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Material.isInteractable()Z
        at think.rpgitems.Events.onPlayerAction(Events.java:299) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_181]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:304) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
        ... 17 more
pl
[17:58:57 INFO]: Plugins (21): MultiWorld, PluginConstructorAPI, SkinsRestorer,
WorldEdit, Essentials, EssentialsProtect, EssentialsChat, GroupManager, ClearLag
, EssentialsAntiBuild, iConomy, LangUtils, Vault, ActionHealth, EssentialsSpawn,
 ProtocolLib, WorldGuard, NyaaCore, RPGItems, Shopkeepers, HolographicDisplays

**Comment by cyilin** [comment]
rpgitems 3.6.415 only support spigot 1.13.1, please update your server version.
