### ISSUE TITLE
RPGItems不兼容新版本WG WE的API

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/RPGitems-reloaded#337]
[18:49:27 INFO]: [RPGItems] [RPGItems] WorldGuard version: 7.0.0-SNAPSHOT;1749-a6261b9 found
[18:49:27 INFO]: [WorldGuard] Registering session handler think.rpgitems.support.WGHandler
[18:49:27 WARN]: java.lang.RuntimeException: Failed to invoke subcommand
[18:49:27 WARN]: at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:211)
[18:49:27 WARN]: at think.rpgitems.power.RPGCommandReceiver.onCommand(RPGCommandReceiver.java:267)
[18:49:27 WARN]: at pw.yumc.Yum.inject.CommandInjector.onCommand(CommandInjector.java:106)
[18:49:27 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[18:49:27 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[18:49:27 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:729)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1769)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1573)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[18:49:27 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:49:27 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[18:49:27 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[18:49:27 WARN]: at java.lang.Thread.run(Thread.java:748)
[18:49:27 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[18:49:27 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:49:27 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:49:27 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:49:27 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[18:49:27 WARN]: at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:204)
[18:49:27 WARN]: ... 18 more
[18:49:27 WARN]: at think.rpgitems.support.WGHandler.refreshPlayerWG(WGHandler.java:103)
[18:49:27 WARN]: at think.rpgitems.support.WGSupport.reload(WGSupport.java:84)
[18:49:27 WARN]: at think.rpgitems.Handler.reload(Handler.java:60)
[18:49:27 WARN]: ... 23 more

**Comment by Ghost-chu** [comment]
CMI调用WG API也会触发此报错
