### ISSUE TITLE
Need help, plugin not working

### ISSUE THREAD

**Issue by Expancion** [NyaaCat/RPGitems-reloaded#341]
`[19:45:06 ERROR]: Could not load 'plugins\rpgitem-reloaded-3.6.457-mc1.13.1.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: LangUtils
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:317) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot-1.13.1.jar:git-Spigot-6b015b4-94b8708]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

**Comment by Librazy** [comment]
Download LangUtils at  https://github.com/NyaaCat/LanguageUtils/releases. 3.6 version needs some more dependencies.
