### ISSUE TITLE
插件在进行部分操作后疯狂报错

### ISSUE THREAD

**Issue by NyanMeow** [NyaaCat/RPGItems-reloaded#354]
# 问题反馈
我是一个paper1.13.2的服务器，在RGI插件进行一些操作之后，服务器开始疯狂刷报错，logs最高都能刷到10M+

## 重现问题

重现问题的步骤：

1. 修改RGI道具信息

### 截图

![QQ截图20190131124258.png](https://i.loli.net/2019/01/31/5c527ceb80319.png)

突然的报错

### 日志

`[10:35:50] [Server thread/WARN]: [RPGItems] Task #104075 for RPGItems v3.7.575-mc1.13.2 generated an exception
java.lang.IllegalArgumentException: `The found tag instance cannot store Integer as it is a NBTTagString
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.CraftCustomTagTypeRegistry.extract(CraftCustomTagTypeRegistry.java:211) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.inventory.tags.CraftCustomItemTagContainer.getCustomTag(CraftCustomItemTagContainer.java:65) ~[patched_1.13.2.jar:git-Paper-509]
	at think.rpgitems.utils.ItemTagUtils.getInt(ItemTagUtils.java:73) ~[?:?]
	at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:493) ~[?:?]
	at think.rpgitems.Events$1.run(Events.java:457) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

## 环境

- Java 版本：[下方图片 ]
- 服务端版本：[ 下方图片 ]
- RPGItems 版本：[ rpgitem-reloaded-3.7.575-mc1.13.2 ]

![QQ截图20190131124418.png](https://i.loli.net/2019/01/31/5c527d2ad2733.png)

##补充

如果需要完整日志文件，我可以提供（涉及部分玩家IP等信息就先不放了

**Comment by Librazy** [comment]
在报错之前是否有在低版本的paper/spigot上使用过该版本（3.7.575，或其它3.7版本）的RGI？
创一个全新的物品是否会有此报错？
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NyanMeow** [comment]
是有过在低版本paper用过这个版本
创建新物品仍旧存在报错

**Comment by Librazy** [comment]
先清除身上所有的rgi物品，如果还有报错说明是其他人身上物品的问题。测试时确保服里只有你一个玩家。

On January 31, 2019 1:19:32 PM GMT+08:00, SakuraShin <notifications@github.com> wrote:
>是有过在低版本paper用过这个版本
>创建新物品仍旧存在报错
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NyaaCat/RPGItems-reloaded/issues/354#issuecomment-459219289

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NyanMeow** [comment]
全新服务器制作全新物品没有发现报错问题

**Comment by Librazy** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-4577 目前无解，请重新生成物品
