### ISSUE TITLE
请求新功能 保存权杖

### ISSUE THREAD

**Issue by 17windy** [NyaaCat/RPGitems-reloaded#40]
自动触发 在玩家生命值小于等于X点的时候 自动使用/spawn指令

**Comment by Taiterio** [comment]
What item should this be put on? Adding a cooldown and health trigger option. Could cause a lot of rage among players xD

**Comment by Taiterio** [comment]
Added in commit cd6806c0582595bb1895efaf3e382991040afeb5

**Comment by phoenixlzx** [comment]
How can this power be added?

I tried with `/rpgitem test_item power rescue 6000 2 true` and get this in console:

```
[00:09:11 WARN]: java.lang.reflect.InvocationTargetException
[00:09:11 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:09:11 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:09:11 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:09:11 WARN]:        at java.lang.reflect.Method.invoke(Method.java:497)
[00:09:11 WARN]:        at think.rpgitems.commands.Commands.exec(Commands.java:186)
[00:09:11 WARN]:        at think.rpgitems.Plugin.onCommand(Plugin.java:124)
[00:09:11 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[00:09:11 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[00:09:11 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[00:09:11 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:09:11 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[00:09:11 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[00:09:11 WARN]:        at java.lang.Thread.run(Thread.java:745)
[00:09:11 WARN]: Caused by: java.util.IllegalFormatConversionException: d != java.lang.Double
[00:09:11 WARN]:        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
[00:09:11 WARN]:        at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
[00:09:11 WARN]:        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
[00:09:11 WARN]:        at java.util.Formatter.format(Formatter.java:2520)
[00:09:11 WARN]:        at java.util.Formatter.format(Formatter.java:2455)
[00:09:11 WARN]:        at java.lang.String.format(String.java:2940)
[00:09:11 WARN]:        at think.rpgitems.power.PowerRescue.displayText(PowerRescue.java:37)
[00:09:11 WARN]:        at think.rpgitems.item.RPGItem.getTooltipLines(RPGItem.java:459)
[00:09:11 WARN]:        at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:328)
[00:09:11 WARN]:        at think.rpgitems.item.RPGItem.addPower(RPGItem.java:813)
[00:09:11 WARN]:        at think.rpgitems.item.RPGItem.addPower(RPGItem.java:788)
[00:09:11 WARN]:        at think.rpgitems.PowerHandler.rescue(PowerHandler.java:455)
[00:09:11 WARN]:        ... 22 more
```
