### ISSUE TITLE
Two problem about version and language

### ISSUE THREAD

**Issue by xiakexiaohei** [NyaaCat/RPGItems-reloaded#417]
Excuse me,I really like your plugin,but I have a problem that I can not use it very well.
I have downloaded the latest version of the plugin and the Dependencies it is latest too.
But still error and asked Is it up to date.
and language have bug too.
I change language to zh_CN,
but it Missing language key.
Is these a bug?

## Environment

- Java version: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.241-b07)
- Server software version:  This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
- RPGItems version: RPGItem v3.8-16 (1.14.4 branch, 760b581)

[org.bukkit.craftbukkit.v1_14_R1.CraftServer] com/udojava/evalex/Expression$LazyNumber initializing RPGItems v3.8-16 (Is it up to date?)
java.lang.NoClassDefFoundError: com/udojava/evalex/Expression$LazyNumber
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_241]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[patched_1.14.4.jar:git-Paper-243]       
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.14.4.jar:git-Paper-243]    
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.14.4.jar:git-Paper-243]        
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-243]        
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at cat.nyaa.nyaacore.utils.ClassPathUtils$ClassInfo.load(ClassPathUtils.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_241]
        at cat.nyaa.nyaacore.utils.ClassPathUtils.scanSubclasses(ClassPathUtils.java:56) ~[?:?]
        at cat.nyaa.nyaacore.utils.ClassPathUtils.scanSubclasses(ClassPathUtils.java:75) ~[?:?]
        at think.rpgitems.power.PowerManager.registerPackage(PowerManager.java:197) ~[?:?]
        at think.rpgitems.power.PowerManager.registerPowers(PowerManager.java:208) ~[?:?]
        at think.rpgitems.RPGItems.onLoad(RPGItems.java:97) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.14.4.jar:git-Paper-243]        
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: com.udojava.evalex.Expression$LazyNumber
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-243]       
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-243]        
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 27 more

**Comment by ReinWD** [comment]
use shadowed NyaaCore [here](https://ci.nyaacat.com/job/NyaaCore/) instead of normal one.
this shadowed jar contains EvalEx from com.udojava that support exciting new feature: eval damage.
