### ISSUE TITLE
Bugs happening on the rescue power

### ISSUE THREAD

**Issue by engineer1109** [NyaaCat/RPGItems-reloaded#420]
# Bug Report

## Describe the Bug

There is a bug about the rescue power (use-bed=true). The player will be removed from the server when he uses the rescue without beds (the player don't set a bed). The player cannot talk and break blocks and use commands. He is like a fake player in the server.

有一个关于rescue power的bug。玩家如果没有设置床，在使用use-bed=true的power 会被服务器移除。玩家会变成一个假玩家，不能说话和使用命令，他好像从服务器消失了，但实际上依旧在线。

## To Reproduce

1.  A new player without setting beds.
2. use the rescue power with use-bed=true

1. 一个新玩家不设置床
2. 使用use-bed=true的rescue power

## Environment

- Java version: 241
- Server software version:  1.15.2 paper
- RPGItems version:  3.8 #76

**Comment by ReinWD** [comment]
后台报错有吗 有的话麻烦贴到paste bin里方便我们检查处理哦

**Comment by engineer1109** [comment]
@ReinWD 
# log
```
[00:54:51] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to RPGItems v3.8-76
java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.server.v1_15_R1.WorldServer.removeEntity(WorldServer.java:1438) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.WorldServer.removePlayer(WorldServer.java:1458) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:606) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:797) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:491) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at think.rpgitems.power.impl.Rescue$Impl.rescue(Rescue.java:132) ~[?:?]
	at think.rpgitems.power.impl.Rescue$Impl.takeHit(Rescue.java:153) ~[?:?]
	at think.rpgitems.power.trigger.HitTaken.run(HitTaken.java:48) ~[?:?]
	at think.rpgitems.power.trigger.HitTaken.run(HitTaken.java:15) ~[?:?]
	at think.rpgitems.power.trigger.Trigger.run(Trigger.java:159) ~[?:?]
	at think.rpgitems.item.RPGItem.power(RPGItem.java:1046) ~[?:?]
	at think.rpgitems.item.RPGItem.power(RPGItem.java:1070) ~[?:?]
	at think.rpgitems.Events.playerHitTaken(Events.java:901) ~[?:?]
	at think.rpgitems.Events.onPlayerHitTaken(Events.java:892) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor758.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:232) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:999) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:886) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:842) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1031) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity0(EntityHuman.java:878) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityHuman.damageEntity(EntityHuman.java:801) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityPlayer.damageEntity(EntityPlayer.java:748) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.World.a(World.java:858) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

[00:55:00] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_15_R1.ChunkMapDistance.b(ChunkMapDistance.java:230) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1362) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:811) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1145) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

**Comment by engineer1109** [comment]
@ReinWD  https://paste.ubuntu.com/p/Byps7Ppfmp/

**Comment by engineer1109** [comment]
Removing entity while ticking
Player被remove了

**Comment by ReinWD** [comment]
好的 周末左右会去调查一下这个问题
似乎是传送时候的MC内部调用出了问题

**Comment by Clexus** [comment]
修了？
