### ISSUE TITLE
Bugs About Throwing entity

### ISSUE THREAD

**Issue by engineer1109** [NyaaCat/RPGItems-reloaded#421]
# Bug Report

## Describe the Bug

The power throwing entity is not work.

/rpgitem power add throw throw cooldown:0 entityName:zombie speed:1 display:z

### Stacktrace or log

```
[21:21:14] [Server thread/WARN]: [RPGItems] Execption spawning entity in throw
java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.ChunkRegionLoader.a(net.minecraft.server.v1_15_R1.NBTTagCompound, net.minecraft.server.v1_15_R1.World, double, double, double, boolean)
	at java.lang.Class.getMethod(Class.java:1786) ~[?:1.8.0_241]
	at think.rpgitems.power.impl.Throw$Impl.summonEntity(Throw.java:142) ~[?:?]
	at think.rpgitems.power.impl.Throw$Impl.fire(Throw.java:116) ~[?:?]
	at think.rpgitems.power.impl.Throw$Impl.rightClick(Throw.java:179) ~[?:?]
	at think.rpgitems.power.trigger.RightClick.run(RightClick.java:20) ~[?:?]
	at think.rpgitems.power.trigger.RightClick.run(RightClick.java:9) ~[?:?]
	at think.rpgitems.power.trigger.Trigger.run(Trigger.java:159) ~[?:?]
	at think.rpgitems.item.RPGItem.power(RPGItem.java:1046) ~[?:?]
	at think.rpgitems.item.RPGItem.power(RPGItem.java:1070) ~[?:?]
	at think.rpgitems.Events.onPlayerAction(Events.java:353) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor769.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:426) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1417) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1172) ~[Paper-1.15.2-b126.jar:git-Paper-125]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[Paper-1.15.2-b126.jar:git-Paper-125]
```

## To Reproduce

1. /rpgitem power add throw throw cooldown:0 entityName:zombie speed:1 display:z

## Environment

- Java version: 241
- Server software version:  paperspigot 1.15.2
- RPGItems version:   3.8-76

中文：
RPGitems的 throw用不了，
spawn entity error.

**Comment by engineer1109** [comment]
https://paste.ubuntu.com/p/ZfYhfCnNSD/

**Comment by Clexus** [comment]
修了
