### ISSUE TITLE
1.12 have bug?

### ISSUE THREAD

**Issue by GTBelo** [NyaaCat/RPGItems-reloaded#441]
Hello, I would like to know if the version of RPGitems for 1.12.2 has any dupe item bug or serious bug.

**Comment by chunye666** [comment]
I download the rpgitem-reloaded-1.12-v.276.jar and I use it in my MC Server.But I found the config.yml is empty.And this prevents me from using the plugin properly.Then I try to input /rpgitem to the chat line,and it show me "An internal error occurred while attempting to perform this command."
When I checked the server backend, I found these errors in the command prompt:
“[17:10:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rpgitem' in plugin RPGItems v3.6.276
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:git-CatServer-1.12.2-74a3a50]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[SimpleCommandMap.class:git-CatServer-1.12.2-74a3a50]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[CraftServer.class:git-CatServer-1.12.2-74a3a50]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1596) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1439) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_261]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:834) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:771) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:625) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at think.rpgitems.commands.RPGCommandReceiver.onCommand(RPGCommandReceiver.java:169) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:git-CatServer-1.12.2-74a3a50]
        ... 15 more”
I want to know what happend.And how can I use this plugin normally.
Thanks for listening.

**Comment by Clexus** [comment]
https://github.com/NyaaCat/RPGItems-reloaded/issues/446#issuecomment-765175928
