### ISSUE TITLE
/rpgitem Give doesn't work

### ISSUE THREAD

**Issue by Shuboh** [NyaaCat/RPGItems-reloaded#443]
# Bug Report

## Describe the Bug
the command rpgitem give doesn't work, i got an internal error

## To Reproduce
/rpgitem create something
/rpgitem give something

### Screenshots
https://cdn.discordapp.com/attachments/780458977930510346/793269519316680744/unknown.png

## Additional Context
[01:05:27] [Server thread/WARN]: java.lang.RuntimeException: Failed to invoke subcommand
[01:05:27] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.acceptCommand(CommandReceiver.java:342)
[01:05:27] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.onCommand(CommandReceiver.java:296)
[01:05:27] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:05:27] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[01:05:27] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
[01:05:27] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[01:05:27] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[01:05:27] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[01:05:27] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:05:27] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:05:27] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:05:27] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:05:27] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver$SubCommandInfo.callCommand(CommandReceiver.java:78)
[01:05:27] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.acceptCommand(CommandReceiver.java:325)
[01:05:27] [Server thread/WARN]:        ... 19 more
[01:05:27] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/utils/ItemTagUtils
[01:05:27] [Server thread/WARN]:        at think.rpgitems.item.RPGItem.updateItem(RPGItem.java:610)
[01:05:27] [Server thread/WARN]:        at think.rpgitems.item.RPGItem.toItemStack(RPGItem.java:1186)
[01:05:27] [Server thread/WARN]:        at think.rpgitems.item.RPGItem.give(RPGItem.java:1353)
[01:05:27] [Server thread/WARN]:        at think.rpgitems.AdminCommands.giveItem(AdminCommands.java:434)
[01:05:27] [Server thread/WARN]:        ... 25 more
[01:05:27] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: cat.nyaa.nyaacore.utils.ItemTagUtils
[01:05:27] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[01:05:27] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[01:05:27] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[01:05:27] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[01:05:27] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[01:05:27] [Server thread/WARN]:        ... 29 more

**Comment by ReinWD** [comment]
update your NyaaCore.
you can find more installation tips [here](https://github.com/NyaaCat/RPGItems-reloaded/issues/444#issuecomment-752341028)
