### ISSUE TITLE
Spigot 1.16.4 Server "Internal server error. Unable to run command."

### ISSUE THREAD

**Issue by LaptisMinecraft** [NyaaCat/RPGItems-reloaded#444]
I downloaded RPGItems and NyaaCore plugin from Jenkins.
> _RPGItems: mc1.16.1-3.81.16-7-release_
> _NyaaCore: mc1.16.4-8.0.18_

Server **CAN** start normally. I can use commands like "_/rpgitem version_", "_/rpgitem give_".
**BUT** when I run "_/rpgitem create itemname_", on client-side I can see "Internal server error. Unable to run command." and cause some exceptions on server-side.

# Server Info
### Server Version
> _Spigot 1.16.4_
### Bukkit Info
```
>icanhasbukkit
[21:19:16] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[21:19:16] [Server thread/INFO]: Checking version, please wait...
[21:19:20] [Thread-39/INFO]: You are 8 version(s) behind
```
### Plugins
```
>plugins
[21:21:19] [Server thread/INFO]: Plugins (46): PluginConstructorAPI, WorldEdit, ServerMonitor, AntiCreeper, SX-Skada, GroupManager, PlaceholderAPI, PlugMan, IllegalStack, BackpacksRemastered, AdvancedPortals, PixelPrinter, BanItem, LangUtils, CS-CoreLib, CustomGo-Tili, ViaVersion, Trush, Vault, ViaBackwards, ViaRewind, ChatColor2, Essentials, Multiverse-Core, ProtocolLib, NyaaCore, CustomGo, Shopkeepers, CustomGo_Divider, EssentialsProtect, CustomGo-SpInv, EssentialsChat, TradePlus, CustomGo-SpRoom, EssentialsSpawn, CustomGo_Leader, RPGItems, CustomGo-Teams, ScoreboardStats, HolographicDisplays, CustomGo-DailyJoin, MythicMobs, AttributePlus, PlayerTitle, Slimefun, Residence
```
### Java Info
> _System Info: Java 1.8 (Java HotSpot(TM) 64-Bit Server VM 25.251-b08) Host: Windows Server 2016 10.0 (amd64)_

# Exception Message:
```
>rpgitem create itemname
[21:13:52] [Server thread/WARN]: java.lang.RuntimeException: Failed to invoke subcommand
[21:13:52] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.acceptCommand(CommandReceiver.java:328)
[21:13:52] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.onCommand(CommandReceiver.java:283)
[21:13:52] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[21:13:52] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[21:13:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:758)
[21:13:52] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:743)
[21:13:52] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387)
[21:13:52] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356)
[21:13:52] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008)
[21:13:52] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847)
[21:13:52] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[21:13:52] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[21:13:52] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
[21:13:52] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:13:52] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:13:52] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:13:52] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[21:13:52] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver$SubCommandInfo.callCommand(CommandReceiver.java:477)
[21:13:52] [Server thread/WARN]:        at cat.nyaa.nyaacore.cmdreceiver.CommandReceiver.acceptCommand(CommandReceiver.java:311)
[21:13:52] [Server thread/WARN]:        ... 11 more
[21:13:52] [Server thread/WARN]: Caused by: java.lang.NoClassDefFoundError: com/udojava/evalex/LazyFunction
[21:13:52] [Server thread/WARN]:        at think.rpgitems.item.RPGItem.getTooltipLines(RPGItem.java:1139)
[21:13:52] [Server thread/WARN]:        at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:1113)
[21:13:52] [Server thread/WARN]:        at think.rpgitems.item.RPGItem.<init>(RPGItem.java:158)
[21:13:52] [Server thread/WARN]:        at think.rpgitems.item.ItemManager.newItem(ItemManager.java:588)
[21:13:52] [Server thread/WARN]:        at think.rpgitems.AdminCommands.createItem(AdminCommands.java:403)
[21:13:52] [Server thread/WARN]:        ... 17 more
[21:13:52] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.udojava.evalex.LazyFunction
[21:13:52] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[21:13:52] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[21:13:52] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[21:13:52] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[21:13:52] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[21:13:52] [Server thread/WARN]:        ... 22 more
[21:13:52] [Server thread/INFO]: Internal server error. Unable to run command.
```

# Others
I noticed that when enabling RPGItems also will caused an exception.
```
[20:55:32] [Server thread/INFO]: [RPGItems] Loading RPGItems v3.81.16-7
[20:55:32] [Server thread/INFO]: [RPGItems] Plugin serial: '0', native version: 'null', server version: '1.16.4'.
[20:55:32] [Server thread/INFO]: [RPGItems] Loading powers...
[20:55:33] [Server thread/ERROR]: com/udojava/evalex/Expression$LazyNumber initializing RPGItems v3.81.16-7 (Is it up to date?)
java.lang.NoClassDefFoundError: com/udojava/evalex/Expression$LazyNumber
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_251]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:202) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:107) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at cat.nyaa.nyaacore.utils.ClassPathUtils$ClassInfo.load(ClassPathUtils.java:245) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_251]
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:1.8.0_251]
        at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:1.8.0_251]
        at cat.nyaa.nyaacore.utils.ClassPathUtils.scanSubclasses(ClassPathUtils.java:68) ~[?:?]
        at cat.nyaa.nyaacore.utils.ClassPathUtils.scanSubclasses(ClassPathUtils.java:87) ~[?:?]
        at think.rpgitems.power.PowerManager.registerPackage(PowerManager.java:204) ~[?:?]
        at think.rpgitems.power.PowerManager.registerPowers(PowerManager.java:215) ~[?:?]
        at think.rpgitems.RPGItems.loadPowers(RPGItems.java:105) ~[?:?]
        at think.rpgitems.RPGItems.onLoad(RPGItems.java:89) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:388) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: com.udojava.evalex.Expression$LazyNumber
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.4.jar:git-Spigot-a19903d-5b74714]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        ... 29 more
```

**Comment by ReinWD** [comment]
plz use "shadowded"  release of NyaaCore.
u can find all NyaaCore release [here](https://ci.nyaacat.com/job/NyaaCore/job/1.16/)
or follow [installation instructions](https://nyaacat.github.io/RPGItems-wiki/#/en-us/installation).
