### ISSUE TITLE
rpgitem is spamming on my console

### ISSUE THREAD

**Issue by Panjiarka** [NyaaCat/RPGItems-reloaded#445]
# Bug Report

## My rpgitem is spamming on my console 

`11:19:31 WARN]: [RPGItems] Task #2050 for RPGItems v3.8-107 generated an exception
java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/utils/ItemTagUtils
        at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:504) ~[?:?]
        at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:490) ~[?:?]
        at think.rpgitems.power.Ticker.run(Ticker.java:27) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1196) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1123) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:943) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
`[12:17:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.8-107
java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/utils/ItemTagUtils
	at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:504) ~[?:?]
	at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:490) ~[?:?]
	at think.rpgitems.Events.onPlayerAction(Events.java:380) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor826.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:158) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1326) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1049) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1042) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1183) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:943) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at java.lang.Thread.run(Thread.java:834) [?:?]`
`[12:17:22] [Server thread/ERROR]: Could not pass event BlockBreakEvent to RPGItems v3.8-107
java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/utils/ItemTagUtils
	at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:504) ~[?:?]
	at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:490) ~[?:?]
	at think.rpgitems.Events.onBlockBreak(Events.java:164) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor832.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:334) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:293) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:261) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1326) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1049) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1042) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1026) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:948) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at java.lang.Thread.run(Thread.java:834) [?:?]`
`[12:17:22] [Server thread/ERROR]: Could not pass event PlayerItemDamageEvent to RPGItems v3.8-107
java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/utils/ItemTagUtils
	at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:504) ~[?:?]
	at think.rpgitems.item.ItemManager.toRPGItem(ItemManager.java:490) ~[?:?]
	at think.rpgitems.Events.onItemDamage(Events.java:970) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor839.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.ItemStack.isDamaged(ItemStack.java:408) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.ItemStack.damage(ItemStack.java:438) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.ItemTool.a(SourceFile:44) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.ItemStack.a(ItemStack.java:471) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:390) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:293) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:261) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1326) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1049) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1042) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1026) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:948) ~[patched_1.15.2.jar:git-YAPFA-"2c1efb1"]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

i cant use ingame commands "internal server eror, unable to run command"

its spamming really fast so i use the logs to copy the errors

- Java version: [ 11 ]
- Server software version: [ git-YAPFA-"2c1efb1" (MC:1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
- RPGItems version: [ RPGItem v3.8-107 (1.15 branch, 0b76988) ]

pls help me i really need this plugin for my server
im new to github btw

**Comment by ReinWD** [comment]
follow [this](https://github.com/NyaaCat/RPGItems-reloaded/issues/444#issuecomment-752341028) and upgrade your NyaaCore.
