### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by TypicalShavonne** [NyaaCat/RPGItems-reloaded#458]
# Bug Report
Console error
## Describe the Bug
it spam my console with this: 
[09:40:45 ERROR]: Could not pass event EntityDamageByEntityEvent to RPGItems v3.81.16-6
java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer
        at think.rpgitems.item.RPGItem$DynamicMethodInterceptor.makeProxy(RPGItem.java:1541) ~[?:?]
        at think.rpgitems.item.RPGItem$DynamicMethodInterceptor.lambda$create$2(RPGItem.java:1551) ~[?:?]
        at java.util.Map.computeIfAbsent(Map.java:1004) ~[?:?]
        at think.rpgitems.item.RPGItem$DynamicMethodInterceptor.create(RPGItem.java:1551) ~[?:?]
        at think.rpgitems.item.RPGItem.lambda$getPower$22(RPGItem.java:1529) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at think.rpgitems.item.RPGItem.getPower(RPGItem.java:1533) ~[?:?]
        at think.rpgitems.item.RPGItem.power(RPGItem.java:1031) ~[?:?]
        at think.rpgitems.item.RPGItem.power(RPGItem.java:1070) ~[?:?]
        at think.rpgitems.Events.playerDamager(Events.java:802) ~[?:?]
        at think.rpgitems.Events.onDamage(Events.java:735) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor503.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1158]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1158]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1158]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1158]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Purpur-1158]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1106) ~[patched_1.16.5.jar:git-Purpur-1158]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:991) ~[patched_1.16.5.jar:git-Purpur-1158]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:946) ~[patched_1.16.5.jar:git-Purpur-1158]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1138) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1977) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1287) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.EntityInsentient.damageEntity(EntityInsentient.java:347) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1255) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2289) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2546) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1158]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1158]
        at java.lang.Thread.run(Thread.java:831) [?:?]

## To Reproduce

1. Use an RPGItems powered item to kill a mob

### Stacktrace or log

If applicable, add stacktrace or log during the issue.

## Environment

- Java version: [ 16 ]
- Server software version: [ This server is running Purpur version git-Purpur-1158 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 18 version(s) behind
Previous version: git-Airplane-"8c50125" (MC: 1.16.5)]
- RPGItems version: [ v3.81.16-6 ]

**Comment by jhooc77** [comment]
You need add `--illegal-access=permit` to jvm flag to use rpgitem with java 16.
But it just temporary solution. RPGItem should remove cglib dependency or find another solution.

**Comment by TypicalShavonne** [comment]
ok
