### ISSUE TITLE
I can't use it in my Paper 1.12.2 server

### ISSUE THREAD

**Issue by Xav1erSue** [NyaaCat/RPGItems-reloaded#461]
# Bug Report

I can't use it in my Paper-1.12.2-b1618 server

## Describe the Bug

alert 
An internal error occurred while attempting to perform this command
when enter /rpgitem

## To Reproduce

1. start server
2. enter /rpgitem

### Stacktrace or log
/rpgitem
null
org.bukkit.command.CommandException: Unhandled exception executing command 'rpgitem' in plugin RPGItems v3.6.248
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_291]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
        at think.rpgitems.commands.RPGCommandReceiver.onCommand(RPGCommandReceiver.java:170) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Paper-1.12.2-b1618.jar:git-Paper-1618]
        ... 15 more
## Environment

- Java version: [ jre8 ]
- Server software version: [ Paper-1.12.2-b1618 ]
- RPGItems version: [ 1.12-v.* ]

## Additional Context

is that because RPGITEMS can't be loaded in PaperSpigot?

**Comment by jhooc77** [comment]
v3.6.248 is old version.
You should read [Installation Guide](https://nyaacat.github.io/RPGItems-wiki/#/en-us/installation)
Use [this](https://github.com/NyaaCat/RPGitems-reloaded/releases/download/1.11-v3.5.448/rpgitem-reloaded-mc1.11-v3.5.448.jar) version.

**Comment by Xav1erSue** [comment]
Solved. I choose the old version because when I use the latest one, it still not working. Maybe that's because the website I visited had used the old one. All in all, thanks for help!
