### ISSUE TITLE
Please Update to 1.20.1

### ISSUE THREAD

**Issue by Koekieezz** [NyaaCat/RPGItems-reloaded#472]
im an old player trying to find a way to make "guns" or wand that could shoot projectile. Im used to rpgitem and i know how to use it, like making a stick that shoots fireball or snowball then add the effects on impact.

Please update to 1.20.1 :")

**Comment by welove69** [comment]
Yes, rpgitem is very easy to use and easy to operate, I like it very much, my favorite

**Comment by i2cy** [comment]
同求

**Comment by Lori3f6** [comment]
Now the main branch is updated to 1.20.4 but not tested yet. It's welcome to have a try and give some feedback if you like :)

**Comment by Lori3f6** [comment]
You can download it from [nyaacat ci](https://ci.nyaacat.com/job/RPGItems-reloaded/job/main/).
And use [Nyaacore](https://github.com/NyaaCat/NyaaCore) [(1.20.4, ci)](https://ci.nyaacat.com/job/NyaaCore/job/main/) as a dependency.

**Comment by Koekieezz** [comment]
> You can download it from [nyaacat ci](https://ci.nyaacat.com/job/RPGItems-reloaded/job/main/). And use [Nyaacore](https://github.com/NyaaCat/NyaaCore) [(1.20.4, ci)](https://ci.nyaacat.com/job/NyaaCore/job/main/) as a dependency.

can it be used with paper/purpur 1.20.1?

**Comment by Koekieezz** [comment]
> You can download it from [nyaacat ci](https://ci.nyaacat.com/job/RPGItems-reloaded/job/main/). And use [Nyaacore](https://github.com/NyaaCat/NyaaCore) [(1.20.4, ci)](https://ci.nyaacat.com/job/NyaaCore/job/main/) as a dependency.

NyaaCore gave me this:
[02:39:34 ERROR]: Error occurred while enabling NyaaCore v${version} (Is it up to date?)
java.lang.NoSuchMethodError: 'net.minecraft.WorldVersion net.minecraft.SharedConstants.getCurrentVersion()'
        at cat.nyaa.nyaacore.NyaaCoreLoader.onEnable(NyaaCoreLoader.java:54) ~[NyaaCore-9.3.4-1.20.4-dev.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
        
RPGItems Release 3.9.6 gave me this:
[02:39:46 ERROR]: Error occurred while enabling RPGItems v3.9.6 (Is it up to date?)
java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/cmdreceiver/CommandReceiver
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:246) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:171) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:246) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:171) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at think.rpgitems.RPGItems.onEnable(RPGItems.java:201) ~[RPGItems-mc1.20.4-3.9.6-release.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2160]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassNotFoundException: cat.nyaa.nyaacore.cmdreceiver.CommandReceiver
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 29 more
        
        
I use purpur 1.20.4, pls help.

**Comment by Clexus** [comment]
这个插件能活到现在是我没想到的，不知道为什么心里有一种感动的感觉

**Comment by Clexus** [comment]
> > You can download it from [nyaacat ci](https://ci.nyaacat.com/job/RPGItems-reloaded/job/main/). And use [Nyaacore](https://github.com/NyaaCat/NyaaCore) [(1.20.4, ci)](https://ci.nyaacat.com/job/NyaaCore/job/main/) as a dependency.
> 
> NyaaCore-9.3.4-1.20.4-dev.jar gave me this: [02:39:34 ERROR]: Error occurred while enabling NyaaCore v${version} (Is it up to date?) java.lang.NoSuchMethodError: 'net.minecraft.WorldVersion net.minecraft.SharedConstants.getCurrentVersion()' at cat.nyaa.nyaacore.NyaaCoreLoader.onEnable(NyaaCoreLoader.java:54) ~[NyaaCore-9.3.4-1.20.4-dev.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2160] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2160] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2160] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2160] at java.lang.Thread.run(Thread.java:842) ~[?:?]
> 
> RPGItems-mc1.20.4-3.9.6-release.jar gave me this: [02:39:46 ERROR]: Error occurred while enabling RPGItems v3.9.6 (Is it up to date?) java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/cmdreceiver/CommandReceiver at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:246) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:171) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:246) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:171) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] at think.rpgitems.RPGItems.onEnable(RPGItems.java:201) ~[RPGItems-mc1.20.4-3.9.6-release.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2160] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2160] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2160] at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2160] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2160] at java.lang.Thread.run(Thread.java:842) ~[?:?] Caused by: java.lang.ClassNotFoundException: cat.nyaa.nyaacore.cmdreceiver.CommandReceiver at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?] at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] ... 29 more
> 
> I use purpur 1.20.4, pls help.

purpur support is not guaranteed
