### ISSUE TITLE
Cannot measure distance between world_nether and world

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#65]
Error log:
```
java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
        at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.Location.distance(Location.java:439) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at think.rpgitems.power.Power.getNearbyEntities(Power.java:55) ~[?:?]
        at think.rpgitems.power.PowerRumble$1.run(PowerRumble.java:96) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

Details can be requested from Melony, UncleVanya and EatMedicine in QQ Group.
cc @RecursiveG

**Comment by RecursiveG** [comment]
Not sure what exactly caused this. Please still keep an eye on it.
