### ISSUE TITLE
Bug with the power rumble in 1.7.10

### ISSUE THREAD

**Issue by xxBoWiExx** [NyaaCat/RPGitems-reloaded#90]
When you do the rumble power, the efect stays in the floor and doesnt desapear, this error is spamed in the console

`[13:53:47] [Server thread/WARN]: [RPGItems] Task #1496 for RPGItems v3.5.102 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
	at think.rpgitems.power.Power.getNearbyEntities(Power.java:48) ~[?:?]
	at think.rpgitems.power.PowerRumble$1.run(PowerRumble.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:701) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
[13:53:47] [Server thread/WARN]: [RPGItems] Task #1496 for RPGItems v3.5.102 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
	at think.rpgitems.power.Power.getNearbyEntities(Power.java:48) ~[?:?]
	at think.rpgitems.power.PowerRumble$1.run(PowerRumble.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:701) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
[13:53:47] [Server thread/WARN]: [RPGItems] Task #1496 for RPGItems v3.5.102 generated an exception
java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
	at think.rpgitems.power.Power.getNearbyEntities(Power.java:48) ~[?:?]
	at think.rpgitems.power.PowerRumble$1.run(PowerRumble.java:96) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:701) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10.jar:git-PaperSpigot-c94b3cd]`

**Comment by Formula350** [comment]
Have you tried it with normal Spigot 1.7.10?
Does it happen in 3.5.99? *(I think it was 3.5.100 where the Rumble between worlds code was added)*

**Comment by RecursiveG** [comment]
The master branch is built against 1.8 and may break with 1.7.X. I will update the 1.7.2 branch and that may be compatible with 1.7.10.

**Comment by RecursiveG** [comment]
try build [v3.5.106](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.7.2-v3.5.106)
