### ISSUE TITLE
[BUG] Power Lifesteal Errors When Applied; Language File Related

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGitems-reloaded#91]
-  This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
  -  RPGItems 3.5.102

Wanted to add the Life Steal power to a bow, but wanted to make sure it worked first so I tossed it on a test item, and this is the error received.

```javascript
[22:35:04] [Server thread/INFO]: Formula350 issued server command: /rpgitem testshovel power lifesteal 7
[22:35:04] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[22:35:04] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:35:04] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:35:04] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:35:04] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.commands.Commands.exec(Commands.java:186)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.Plugin.onCommand(Plugin.java:128)
[22:35:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[22:35:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[22:35:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[22:35:04] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:35:04] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[22:35:04] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[22:35:04] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:35:04] [Server thread/WARN]: Caused by: java.util.IllegalFormatConversionException: d != java.lang.Double
[22:35:04] [Server thread/WARN]: 	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
[22:35:04] [Server thread/WARN]: 	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
[22:35:04] [Server thread/WARN]: 	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
[22:35:04] [Server thread/WARN]: 	at java.util.Formatter.format(Formatter.java:2520)
[22:35:04] [Server thread/WARN]: 	at java.util.Formatter.format(Formatter.java:2455)
[22:35:04] [Server thread/WARN]: 	at java.lang.String.format(String.java:2940)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.power.PowerLifeSteal.displayText(PowerLifeSteal.java:47)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.getTooltipLines(RPGItem.java:477)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:340)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.addPower(RPGItem.java:838)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.item.RPGItem.addPower(RPGItem.java:813)
[22:35:04] [Server thread/WARN]: 	at think.rpgitems.PowerHandler.lifesteal(PowerHandler.java:289)
[22:35:04] [Server thread/WARN]: 	... 22 more
```
That's with the *default* Language file.

As a request, perhaps set it to **not** apply the power if it ends up erroring, as when the server restarts it ends up breaking the plugin.

Should also make it use YAML for the language files, that way I can make the edits I need for quite a few of them that are **way** too long (Area of Effect and Forcefield) ;) ;)

**Comment by RecursiveG** [comment]
See #49 for language file discussion.
You may modify the lang file as a workaround. see #85

**Comment by Formula350** [comment]
I don't know if you prefer a New Issue be opened for this type of thing or not, but given it is specifically related to this I figured I'd add it here...

Seems the `switchpowertext` oversteps its bounds, and removes more than just the Power Description.
`switchpowertext true`: 
![item-before](https://cloud.githubusercontent.com/assets/10291023/14235953/79d1288a-f9da-11e5-9ce1-fdf8bd3dabd9.JPG)
`switchpowertext false`:
![item-after](https://cloud.githubusercontent.com/assets/10291023/14235954/82701514-f9da-11e5-9aa1-22ddc70dd63e.JPG)

As you can see, only the Lore and Description lines remain

**Comment by RecursiveG** [comment]
That's the intended behavior because someone don't want those lines either.
You can still manually add those lines (in form of descriptions) if you want.

**Comment by Formula350** [comment]
Oh, dang, I thought it just was removal of the Powers heh. Adding the `Hand                             Type` is a pain in the butt to re-create in the lore, that and the quotes. The Descriptions would be a viable solution, but they're *below* the Lore.

Still, am grateful for you adding it, as it at least provides a solution to the insane description lengths until I can figure out how to properly truncate them heh
Thanks :)
