### ISSUE TITLE
NoSuchFieldError on spigot 1.9.2

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#92]
```
[15:16:17 ERROR]: Could not pass event PlayerInteractEvent to RPGItems v3.5.104
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:194) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:945) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:27) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchFieldError: ENDERMAN_TELEPORT
        at think.rpgitems.power.PowerTeleport.rightClick(PowerTeleport.java:86) ~[?:?]
        at think.rpgitems.item.RPGItem.rightClick(RPGItem.java:307) ~[?:?]
        at think.rpgitems.Events.onPlayerAction(Events.java:192) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.2.jar:git-Spigot-a1b8bf3-f01861f]
        ... 18 more
```

**Comment by RecursiveG** [comment]
The `master` branch is for spigot 1.8 and may be incompatible with 1.7.x or 1.9.x.
Please use the builds prefixed `1.9` for 1.9 servers.
