### ISSUE TITLE
RPG items-reloaded-102-108 Error 

### ISSUE THREAD

**Issue by lsz7575** [NyaaCat/RPGitems-reloaded#94]
1. 
Thermos-1.7.10-1448-server.jar

2. 
RPG items-reloaded-101     is no problem
RPG items-reloaded-102-108    Error  
Thank you for showing this plugin re-sparkle    :)
If the repair is not good it does not matter, I'll use 101,
Refuel

3. 
Error occurred while enabling RPGItems v3.5.102 (Is it up to date?)
java.lang.NoSuchMethodError: 
org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
	at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:350) ~[?:?]
	at think.rpgitems.item.RPGItem.<init>(RPGItem.java:106) ~[?:?]
	at think.rpgitems.config.Update02To03.update(Update02To03.java:138) ~[?:?]
	at think.rpgitems.config.ConfigUpdater.updateConfig(ConfigUpdater.java:63) ~[?:?]
	at think.rpgitems.Plugin.updateConfig(Plugin.java:113) ~[?:?]
	at think.rpgitems.Plugin.onEnable(Plugin.java:86) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.52]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:285) [PlugMan.jar:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.52]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) [CraftServer.class:1.7.10-1614.52]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1329) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1103) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]

**Comment by RecursiveG** [comment]
Master branch is for 1.8 servers.
Please use those releases prefixed `1.7.2-` for 1.7.x server.
Like [1.7.2-v3.5.106](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.7.2-v3.5.106)

**Comment by lsz7575** [comment]
@RecursiveG  thank you..
sorry, give you trouble
